# Periodically checks the nuget.org V3 service index for changes.
# Inspired by https://simonwillison.net/2020/Oct/9/git-scraping/

name: Update data

on:
  workflow_dispatch:
  schedule:
    - cron: '11 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check PROD
      run: |-
        mkdir -p api.nuget.org/v3
        content=$(curl --silent --show-error --fail --retry 5 --retry-connrefused https://api.nuget.org/v3/index.json)
        echo "$content" | jq . > api.nuget.org/v3/index.json
    - name: Check INT
      run: |-
        mkdir -p apiint.nugettest.org/v3
        content=$(curl --silent --show-error --fail --retry 5 --retry-connrefused https://apiint.nugettest.org/v3/index.json)
        echo "$content" | jq . > apiint.nugettest.org/v3/index.json
    - name: Check DEV
      run: |-
        mkdir -p apidev.nugettest.org/v3
        content=$(curl --silent --show-error --fail --retry 5 --retry-connrefused https://apidev.nugettest.org/v3/index.json)
        echo "$content" | jq . > apidev.nugettest.org/v3/index.json
    - name: Check Azure DevOps nuget-build
      run: |-
        mkdir -p pkgs.dev.azure.com/dnceng/public/_packaging/nuget-build/nuget/v3
        content=$(curl --silent --show-error --fail --retry 5 --retry-connrefused https://pkgs.dev.azure.com/dnceng/public/_packaging/nuget-build/nuget/v3/index.json)
        echo "$content" | jq . > pkgs.dev.azure.com/dnceng/public/_packaging/nuget-build/nuget/v3/index.json
    - name: Check MyGet nuget-build
      run: |-
        mkdir -p dotnet.myget.org/F/nuget-build/api/v3
        content=$(curl --silent --show-error --fail --retry 5 --retry-connrefused https://dotnet.myget.org/F/nuget-build/api/v3/index.json)
        echo "$content" | jq . > dotnet.myget.org/F/nuget-build/api/v3/index.json
    - name: Check GitHub joelverhagen
      run: |-
        mkdir -p nuget.pkg.github.com/joelverhagen
        content=$(curl --silent --show-error --fail --retry 5 --retry-connrefused --basic --user user:password https://nuget.pkg.github.com/joelverhagen/index.json)
        echo "$content" | jq . > nuget.pkg.github.com/joelverhagen/index.json
    - name: Check Cloudsmith joelverhagen
      run: |-
        mkdir -p nuget.cloudsmith.io/joel-verhagen-Ie9/joel-verhagen/v3
        content=$(curl --silent --show-error --fail --retry 5 --retry-connrefused https://nuget.cloudsmith.io/joel-verhagen-Ie9/joel-verhagen/v3/index.json)
        echo "$content" | jq . > nuget.cloudsmith.io/joel-verhagen-Ie9/joel-verhagen/v3/index.json
    - name: Check test BaGet
      run: |-
        mkdir -p bagettest.azurewebsites.net/v3
        content=$(curl --silent --show-error --fail --retry 5 --retry-connrefused https://bagettest.azurewebsites.net/v3/index.json)
        echo "$content" | jq . > bagettest.azurewebsites.net/v3/index.json
    - name: Check feedz.io
      run: |-
        mkdir -p f.feedz.io/joel-verhagen/test-org/nuget
        content=$(curl --silent --show-error --fail --retry 5 --retry-connrefused https://f.feedz.io/joel-verhagen/test-org/nuget/index.json)
        echo "$content" | jq . > f.feedz.io/joel-verhagen/test-org/nuget/index.json
    - name: Commit and push if data has changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
