# Periodically checks the nuget.org V3 service index for changes.
# Inspired by https://simonwillison.net/2020/Oct/9/git-scraping/

name: Update data (test)

on:
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check PROD
      run: |-
        mkdir -p api.nuget.org/v3
        content=$(curl https://api.nuget.org/v3/index.json)
        echo $content | jq . > api.nuget.org/v3/index.json
    - name: Check INT
      run: |-
        mkdir -p apiint.nugettest.org/v3
        content=$(curl https://apiint.nugettest.org/v3/index.json)
        echo $content | jq . > apiint.nugettest.org/v3/index.json
    - name: Check DEV
      run: |-
        mkdir -p apidev.nugettest.org/v3
        content=$(curl https://apidev.nugettest.org/v3/index.json)
        echo $content | jq . > apidev.nugettest.org/v3/index.json
    - name: Check Azure DevOps nuget-build
      run: |-
        mkdir -p pkgs.dev.azure.com/dnceng/public/_packaging/nuget-build/nuget/v3
        content=$(curl https://pkgs.dev.azure.com/dnceng/public/_packaging/nuget-build/nuget/v3/index.json)
        echo $content | jq . > pkgs.dev.azure.com/dnceng/public/_packaging/nuget-build/nuget/v3/index.json
