# Periodically checks the nuget.org V3 service index for changes.
# Inspired by https://simonwillison.net/2020/Oct/9/git-scraping/

name: Update data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '11 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check PROD
      run: |-
        mkdir -p api.nuget.org/v3
        curl https://api.nuget.org/v3/index.json | jq . > api.nuget.org/v3/index.json
    - name: Check INT
      run: |-
        mkdir -p apiint.nugettest.org/v3
        curl https://apiint.nugettest.org/v3/index.json | jq . > apiint.nugettest.org/v3/index.json
    - name: Check DEV
      run: |-
        mkdir -p apidev.nugettest.org/v3
        curl https://apidev.nugettest.org/v3/index.json | jq . > apidev.nugettest.org/v3/index.json
    - name: Commit and push data has changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
